### PR TITLE
Remove `assert_tag` and bump to 2.0

### PR DESCRIPTION
**Pull request by kaspth**
Should be everything we promised for Rails 5.

Then we just release 2.0, and make Rails require it.

Was also thinking we could ditch Ruby < 2.2 testing and require Rails 5.0, because the change is so small and we're bumping major. What do you think, @rafaelfranca?

### CODE REVIEW

**Comment by kaspth** [comment]
On the other hand leaving Rails 4.2 means people would be able to upgrade early and not have that be a point in the Rails 5 update.

**Comment by rafaelfranca** [comment]
I think we need to change jquery-rails to not use assert_tag. Could you take a look?

**Comment by rafaelfranca** [comment]
Ah, it is not using anymore. :shipit:

**Comment by rafaelfranca** [comment]
About dropping support to Rails 4.2 and ruby 2.2 it is better to do after 4.2 is not under maintenance anymore, otherwise we would need a stable branch for this gem and I don't want to release two versions.

**Comment by kaspth** [comment]
Good point, let's revisit then 👍

**Pull request merged**
