### PR TITLE
Update dom_assertions.rb

### PR DESCRIPTION
**Pull request by tofoli**
Ignores line breaks and whitespace

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you for the pull request but why would we do that?

**Comment by chancancode** [comment]
@rafaelfranca I think the is probably motivated by the same thing as #62, but I don't think this is the proper solution, as it doesn't handle the "interior" whitespace

**Comment by rafaelfranca** [comment]
👍

**Comment by wnm** [comment]
@chancancode maybe .gsub(/\s+/, ' ') instead of .strip then?

**Comment by tofoli** [comment]
My field textarea `f.textarea` assembles the value with a line break at the beginning, for example
```
<Textarea>
My Value <textarea>
```

When doing the validation he was comparing "\nMy Value" == "My Value". With `.split` remove this line break so the information stays the same

**Comment by colorfulfool** [comment]
@wnm It has to be `gsub(/\s{2,}/, '')` to do the trick, I just checked.

**Comment by jduff** [comment]
With #84 merged I think it covers the case this PR was for, please give master a try and see if there were any cases missed!

**Pull request closed without merging**
