### PR TITLE
Fix incorrect spelling.

### PR DESCRIPTION
**Pull request by tgxworld**

### CODE REVIEW

**Comment by tgxworld** [comment]
@kaspth Should this be nested under say `Rails::Dom::Testing::CountDescribable`? It is appearing as `CountDescribable` in the ancestors chain making it confusing where it is coming from.

**Comment by kaspth** [comment]
Yeah, let's nest as far down as we can too.

**Comment by tgxworld** [comment]
@kaspth Done :smile:

**Comment by kaspth** [comment]
Ewww, but that's how it goes. Thanks :smile:

**Pull request merged**
